/*
 * Copyright (C) 2026 Andrew S. Rightenburg
 * Bash++: Bash with classes
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#pragma once

#include <IR/bpp.h>
#include <IR/entities/BashFunction.h>
#include <IR/entities/Object.h>
#include <IR/entities/components/Addressable.h>
#include <IR/entities/components/ClassMember.h>
#include <IR/entities/MethodParameter.h>

#include <map>
#include <memory>
#include <optional>
#include <expected>

#include <error/InternalError.h>

namespace bpp::IR {

/**
 * @brief A method in a class
 */
class Method : public BashFunction, public Components::Addressable, public Components::ClassMember {
	private:
		/// List of parameters expected to be given as arguments to the method
		class ParameterList {
			private:
				std::map<std::uint32_t, const MethodParameter*> params;
				std::uint32_t next_index = 0;
			public:
				void add(const MethodParameter* parameter);
				const MethodParameter* getByIndex(std::uint32_t index) const;
				/**
				 * @brief Get all parameters with the given name.
				 * There will be *at most* 2 parameters with the same name: one primitive and one pointer parameter.
				 */
				std::vector<const MethodParameter*> getByName(std::string_view name) const;
				const std::map<std::uint32_t, const MethodParameter*>& view() const { return params; }
				std::uint32_t getNextIndex() const { return next_index; }
				std::optional<std::uint32_t> getHighestIndex() const;
		} parameters;

		/**
		 * @brief A list of parameters that are primitives (i.e., not pointers to objects).
		 *
		 * Pointer parameters are stored in the local objects list rather than this one.
		 *
		 * Since there is no chance of ambiguity between referencing `$arg' and `@arg',
		 * there is no rule against having a primitive parameter and a pointer parameter with the same name.
		 * That being the case, it's important to store the primitive parameters in a separate container.
		 * It also prevents accidental discovery from `@ID` lookups, which should never find pure primitives.
		 *
		 * The ParameterList stores non-owning pointers to both primitive and pointer parameters.
		 * This container (and the local objects list) are the *owners* of the parameters, and are responsible for their lifetime.
		 */
		OwnedEntityList<MethodParameter> primitive_parameters;

		bool f_is_virtual = false;
		bool f_is_overridable = false;

		/**
		 * @brief This flag is set if this method is a defaulted method, i.e., it has no user-defined body and is automatically generated by the compiler.
		 */
		bool f_is_defaulted = false;

		/**
		 * @brief This flag is set if this is an inherited method that has not been overridden.
		 * In that case, there's no sense duplicating the code of the parent method; we'll just call the parent method directly.
		 */
		bool f_points_to_parent_method = false;
	public:
		Method() = default;

		/**
		 * @brief Create a new Method that is inherited (and not overridden) from a parent method.
		 * This method will be a hollow "pointer" to the parent method, and will not generate its own code.
		 * Calls to this method will be redirected to the parent method.
		 * @param parent_method The parent method to inherit from
		 */
		explicit Method(const Method* parent_method) {
			bpp_assert(parent_method != nullptr, "Parent method pointer is null");
			while (parent_method->pointsToParentMethod()) {
				// If the parent method is itself an inherited method that points to its own parent, traverse the chain up to the original method.
				// This is not strictly necessary but will save time later during lookup
				parent_method = parent_method->getParentMethod();
				bpp_assert(parent_method != nullptr, "Parent method pointer is null");
			}
			inherit(parent_method);
			setParentMethod(parent_method);
			setName(parent_method->getName());
			if (parent_method->getScope() == VisibilityScope::PRIVATE) {
				setScope(VisibilityScope::INACCESSIBLE);
			} else {
				setScope(parent_method->getScope());
			}
			setIsVirtual(parent_method->isVirtual());
			setIsOverridable(parent_method->isVirtual());
			setIsDefaulted(parent_method->isDefaulted());
			f_points_to_parent_method = true;
		}
		/**
		 * @brief Add a parameter to this method
		 *
		 * If this parameter's name conflicts with an existing parameter, this method will return false and not add the parameter.
		 *
		 * If the parameter is a pointer to a nonprimitive type, this method will also set up an implicit dynamic cast for the parameter,
		 * and verify that its name does not conflict with any known classes or objects in the containing method's context.
		 * 
		 * @param parameter The parameter to add
		 * @return std::expected<void, NameConflictError> Returns an error if the parameter's name conflicts with an existing parameter, class, or object
		 */
		std::expected<void, NameConflictError> addParameter(std::unique_ptr<MethodParameter> owned_parameter);

		/**
		 * @brief Add a non-owned parameter to this method (e.g., the class's `this` pointer)
		 * This will not modify the parameter in any way, and the method will not take ownership of it.
		 * @param parameter The parameter to add
		 * @return std::expected<void, NameConflictError> Returns an error if the parameter's name conflicts with an existing parameter, class, or object
		 */
		std::expected<void, NameConflictError> addParameter(const MethodParameter* unowned_parameter);

		const std::map<std::uint32_t, const MethodParameter*>& getParameters() const { return parameters.view(); }

		std::string getAddress() const override;

		void setIsVirtual(bool is_virtual) { this->f_is_virtual = is_virtual; }
		bool isVirtual() const { return f_is_virtual; }

		void setIsOverridable(bool is_overridable) { this->f_is_overridable = is_overridable; }
		bool isOverridable() const { return f_is_overridable; }

		void setIsDefaulted(bool is_defaulted) { this->f_is_defaulted = is_defaulted; }
		bool isDefaulted() const { return f_is_defaulted; }

		void setParentMethod(const Method* parent_method) { setParentMember(parent_method); }
		const Method* getParentMethod() const { return static_cast<const Method*>(getParentMember()); }

		bool pointsToParentMethod() const { return f_points_to_parent_method; }

		bpp::CodeGen::CodeSegment generateCode(bpp::CodeGen::CodeGenState* state) const override;

		PRETTYPRINT_OVERRIDE();
};

} // namespace bpp::IR
