name: Bash++
title: Bash++
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings
minima:
  skin: dark
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
header_pages:
  - download.md
