name: Tree-sitter Parser

on:
  pull_request:
    paths:
      - ".github/workflows/tree-sitter.yml"
      - "examples/**/*.bpp"
      - "makefile"
      - "test-suite/**/*.bpp"
      - "tree-sitter-bashpp/**"
      - "wiki/_includes/code/snippets/**/*.bpp"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/tree-sitter.yml"
      - "examples/**/*.bpp"
      - "makefile"
      - "test-suite/**/*.bpp"
      - "tree-sitter-bashpp/**"
      - "wiki/_includes/code/snippets/**/*.bpp"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: tree-sitter-bashpp/package-lock.json

      - name: Install dependencies
        working-directory: tree-sitter-bashpp
        run: npm ci

      - name: Test parser
        run: make test-tree-sitter
